# args
unimodal: False
fusion: False
attention_2: False
use_raw: False
data: "mosi"
classes: 2

# run configuration
gpu_device: 0
batch_size: 20
epochs: 100
verbose: 0

tfprofile: True
tfprofileEvery: 1
tfprofile_dir: "/mnt/Data/yj/mm/tfprofile.msa"